WARNING: Could not find any nv files on this host!
/ext3/miniconda3/lib/python3.9/site-packages/numba/core/cpu.py:97: UserWarning: Numba extension module 'sparse._numba_extension' failed to load due to 'ContextualVersionConflict((numpy 1.22.4 (/ext3/miniconda3/lib/python3.9/site-packages), Requirement.parse('numpy<1.22,>=1.18'), {'numba'}))'.
  numba.core.entrypoints.init_all()
PREPROCESS CASE lat_-57_-42_lon_23_37/
2022-10-05 22:03:38.685625
T,S,U,V,W FROM LLC4320
2022-10-05 22:03:38.685653
/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/indexing.py:1380: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  value = value[(slice(None),) * axis + (subkey,)]
/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/indexing.py:1380: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  value = value[(slice(None),) * axis + (subkey,)]
/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/indexing.py:1380: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  value = value[(slice(None),) * axis + (subkey,)]
/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/indexing.py:1380: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  value = value[(slice(None),) * axis + (subkey,)]
/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/indexing.py:1380: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  value = value[(slice(None),) * axis + (subkey,)]
CALCULATE B
2022-10-06 01:52:56.181332
SAVE SNAPSHOT: B,U,V,W
2022-10-06 02:01:33.234901
SAVE SNAPSHOT: MLD
2022-10-06 02:01:44.504584
FILTER
2022-10-06 02:01:45.377179
COARSE-GRAIN
2022-10-06 03:54:00.541992
/ext3/miniconda3/lib/python3.9/site-packages/dask/array/core.py:450: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  o = func(*args, **kwargs)
MLD AVERAGE
2022-10-06 03:54:31.138988
SAVE NETCDF: MLD AVG LOWRES
meso fields
Traceback (most recent call last):
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 201, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 55, in __getitem__
    value = self._cache[key]
KeyError: [<function _open_scipy_netcdf at 0x1500b9262550>, ('/scratch/ab10313/submeso_ML_data/lat_-57_-42_lon_23_37/data/Um_lowres_MLD.nc',), 'a', (('mmap', None), ('version', 2))]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ab10313/submeso_ML/preprocess_code/preprocess_llc4320_save_lat_-57_-42_lon_23_37.py", line 383, in <module>
    Um_lowres_MLD.to_netcdf(PATH+'data/Um_lowres_MLD.nc')
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/dataarray.py", line 3217, in to_netcdf
    return to_netcdf(  # type: ignore  # mypy cannot resolve the overloads:(
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/backends/api.py", line 1210, in to_netcdf
    dump_to_store(
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/backends/api.py", line 1257, in dump_to_store
    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/backends/common.py", line 266, in store
    self.set_dimensions(variables, unlimited_dims=unlimited_dims)
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/backends/common.py", line 327, in set_dimensions
    existing_dims = self.get_dimensions()
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/backends/scipy_.py", line 181, in get_dimensions
    return Frozen(self.ds.dimensions)
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/backends/scipy_.py", line 163, in ds
    return self._manager.acquire()
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 183, in acquire
    file, _ = self._acquire_with_cache_info(needs_lock)
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 207, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/backends/scipy_.py", line 102, in _open_scipy_netcdf
    return scipy.io.netcdf_file(filename, mode=mode, mmap=mmap, version=version)
  File "/home/ab10313/.local/lib/python3.9/site-packages/scipy/io/netcdf.py", line 247, in __init__
    self.fp = open(self.filename, '%sb' % omode)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/ab10313/submeso_ML_data/lat_-57_-42_lon_23_37/data/Um_lowres_MLD.nc'
