WARNING: Could not find any nv files on this host!
/ext3/miniconda3/lib/python3.9/site-packages/numba/core/cpu.py:97: UserWarning: Numba extension module 'sparse._numba_extension' failed to load due to 'ContextualVersionConflict((numpy 1.22.4 (/ext3/miniconda3/lib/python3.9/site-packages), Requirement.parse('numpy<1.22,>=1.18'), {'numba'}))'.
  numba.core.entrypoints.init_all()
PREPROCESS CASE lat_-57_-42_lon_23_37/
2022-10-09 07:40:43.838751
T,S,U,V,W FROM LLC4320
2022-10-09 07:40:43.838786
Traceback (most recent call last):
  File "/home/ab10313/submeso_ML/preprocess_code/preprocess_llc4320_save_lat_-57_-42_lon_23_37_debug.py", line 57, in <module>
    T_prechunk = ds_T_full.Theta.resample(time='24H').nearest(tolerance="1H").where(sel_area, drop=True)
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/common.py", line 1078, in where
    self = self.isel(**indexers)
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/dataarray.py", line 1283, in isel
    ds = self._to_temp_dataset()._isel_fancy(
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/dataset.py", line 2433, in _isel_fancy
    indexes, index_variables = isel_indexes(self.xindexes, valid_indexers)
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/indexes.py", line 1357, in isel_indexes
    return _apply_indexes(indexes, indexers, "isel")
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/indexes.py", line 1341, in _apply_indexes
    new_index = getattr(index, func)(index_args)
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/indexes.py", line 362, in isel
    return self._replace(self.index[indxr])
  File "/ext3/miniconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5055, in __getitem__
    result = getitem(key)
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/array/core.py", line 1626, in __array__
    x = self.compute()
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/base.py", line 290, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/base.py", line 573, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/threaded.py", line 81, in get
    results = get_async(
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/local.py", line 506, in get_async
    raise_exception(exc, tb)
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/local.py", line 314, in reraise
    raise exc
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/local.py", line 219, in execute_task
    result = _execute_task(task, data)
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/ab10313/.local/lib/python3.9/site-packages/xmitgcm/llcreader/llcmodel.py", line 507, in _get_facet_chunk
    buffer = file.read(read_length)
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/implementations/http.py", line 574, in read
    return super().read(length)
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/spec.py", line 1575, in read
    out = self.cache._fetch(self.loc, self.loc + length)
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/caching.py", line 377, in _fetch
    self.cache = self.fetcher(start, bend)
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/asyn.py", line 111, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/asyn.py", line 96, in sync
    raise return_result
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/asyn.py", line 53, in _runner
    result[0] = await coro
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/implementations/http.py", line 613, in async_fetch_range
    r.raise_for_status()
  File "/home/ab10313/.local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://data.nas.nasa.gov/ecco/download_data.php?file=/eccodata/llc_4320/grid/YC.data')
