WARNING: Could not find any nv files on this host!
/ext3/miniconda3/lib/python3.9/site-packages/numba/core/cpu.py:97: UserWarning: Numba extension module 'sparse._numba_extension' failed to load due to 'ContextualVersionConflict((numpy 1.22.4 (/ext3/miniconda3/lib/python3.9/site-packages), Requirement.parse('numpy<1.22,>=1.18'), {'numba'}))'.
  numba.core.entrypoints.init_all()
PREPROCESS CASE lat_-57_-42_lon_23_37/
2022-10-05 14:31:12.374940
T,S,U,V,W FROM LLC4320
2022-10-05 14:31:12.374983
/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/indexing.py:1380: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  value = value[(slice(None),) * axis + (subkey,)]
/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/indexing.py:1380: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  value = value[(slice(None),) * axis + (subkey,)]
/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/indexing.py:1380: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  value = value[(slice(None),) * axis + (subkey,)]
Traceback (most recent call last):
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/asyn.py", line 53, in _runner
    result[0] = await coro
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/implementations/http.py", line 616, in async_fetch_range
    out = await r.read()
  File "/home/ab10313/.local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1036, in read
    self._body = await self.content.read()
  File "/home/ab10313/.local/lib/python3.9/site-packages/aiohttp/streams.py", line 375, in read
    block = await self.readany()
  File "/home/ab10313/.local/lib/python3.9/site-packages/aiohttp/streams.py", line 397, in readany
    await self._wait("readany")
  File "/home/ab10313/.local/lib/python3.9/site-packages/aiohttp/streams.py", line 304, in _wait
    await waiter
  File "/home/ab10313/.local/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ab10313/submeso_ML/preprocess_code/preprocess_llc4320_save_lat_-57_-42_lon_23_37.py", line 59, in <module>
    U = ds_UV_full_interp.U.resample(time='24H').nearest(tolerance="1H").where(sel_area, drop=True)
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/common.py", line 1078, in where
    self = self.isel(**indexers)
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/dataarray.py", line 1283, in isel
    ds = self._to_temp_dataset()._isel_fancy(
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/dataset.py", line 2443, in _isel_fancy
    new_var = var.isel(indexers=var_indexers)
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/variable.py", line 1226, in isel
    return self[key]
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/variable.py", line 785, in __getitem__
    dims, indexer, new_order = self._broadcast_indexes(key)
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/variable.py", line 646, in _broadcast_indexes
    return self._broadcast_indexes_outer(key)
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/variable.py", line 699, in _broadcast_indexes_outer
    k = np.asarray(k)
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/array/core.py", line 1626, in __array__
    x = self.compute()
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/base.py", line 290, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/base.py", line 573, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/threaded.py", line 81, in get
    results = get_async(
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/local.py", line 506, in get_async
    raise_exception(exc, tb)
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/local.py", line 314, in reraise
    raise exc
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/local.py", line 219, in execute_task
    result = _execute_task(task, data)
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/ab10313/.local/lib/python3.9/site-packages/xmitgcm/llcreader/llcmodel.py", line 507, in _get_facet_chunk
    buffer = file.read(read_length)
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/implementations/http.py", line 574, in read
    return super().read(length)
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/spec.py", line 1575, in read
    out = self.cache._fetch(self.loc, self.loc + length)
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/caching.py", line 377, in _fetch
    self.cache = self.fetcher(start, bend)
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/asyn.py", line 111, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/asyn.py", line 94, in sync
    raise FSTimeoutError from return_result
fsspec.exceptions.FSTimeoutError
